### ISSUE TITLE
Social icons are hard to see in Github's Dark Theme

### ISSUE THREAD

**Issue by vikasganiga05** [priyadarshu/priyadarshu#1]
The social media icons are hard to see to the user with the Github Dark theme enabled. My recommendation is to change the black icons to colored icons.

#### Screenshot

![image](https://user-images.githubusercontent.com/74750414/118402331-13905b80-b687-11eb-8e89-dbbdd9531c9b.png)

**Comment by priyadarshu** [comment]
Thanks for pointing it out @vikasganiga05 , I will change them to colored icons.
Really appreciate the catch !

**Comment by priyadarshu** [comment]
Removed the links to the social accounts as of now.
Will add them later
